module: ml_project.pipeline
class: Pipeline
params:
  class_list:
    # - module: ml_project.models.feature_selection
    #   class: RemoveEmptyValues


    - module: ml_project.models.feature_extraction
      class: BinsExtraction
      params:
        bin_length: 50
        # middle_images_only: True # score: 73.3
        images_x_from: 50
        images_x_to: 130
        more_features: False # score:
        del_zero_std: False

    - module: sklearn.preprocessing
      class: Normalizer

    - module: sklearn.linear_model
      class: LinearRegression
      params:
        n_jobs: -1
    # - module: sklearn.ensemble
    #   class: GradientBoostingRegressor
    #   params:
    #     learning_rate: 0.01
    #     n_estimators: 1000
    #     warm_start: True



    # - module: sklearn.linear_model
    #   class: Lasso
    #   params:
    #     alpha: 0.1
    #     normalize: True
    #     warm_start: True
    #     random_state: 37
