module: ml_project.pipeline
class: Pipeline
params:
  class_list:
    # - module: ml_project.models.feature_selection
    #   class: RemoveEmptyValues


    # - module: ml_project.models.feature_extraction
    #   class: BinsExtraction
    #   params:
    #     # middle_images_only: True # score: 73.3
    #     bin_length: 35
    #     images_x_from: 50
    #     images_x_to: 120
    #     images_y_from: 20
    #     images_y_to: 160
    #     more_features: False # score:
    #     del_zero_std: False
    # - module: ml_project.models.feature_extraction
    #   class: StatsExtraction
    - module: ml_project.models.feature_extraction
      #class: GivenEdgesExtraction
      class: WhatEver
      params:
        splits: 610
        images_x_from: 50
        images_x_to: 130

    - module: sklearn.preprocessing
      class: StandardScaler
    - module: sklearn.feature_selection
      class: VarianceThreshold
      params:
        threshold: 0.2

    - module: sklearn.svm
      class: LinearSVR
      params:
        C: 15.0
        max_iter: 2000

    # - module: sklearn.preprocessing
    #   class: StandardScaler
    #
    # - module: sklearn.kernel_ridge
    #   class: KernelRidge
    #   params:
    #     kernel: 'polynomial'

    # - module: sklearn.linear_model
    #   class: LinearRegression
    #   params:
    #     n_jobs: -1
    # # - module: sklearn.ensemble
    #   class: GradientBoostingRegressor
    #   params:
    #     learning_rate: 0.01
    #     n_estimators: 1000
    #     warm_start: True



    # - module: sklearn.linear_model
    #   class: Lasso
    #   params:
    #     alpha: 0.1
    #     normalize: True
    #     warm_start: True
    #     random_state: 37
